### ISSUE TITLE
Question : Stop Listening

### ISSUE THREAD

**Issue by plwodi** [jweisz/tjbot-playground#1]
How do you terminate the tj.listen(args) function?  I'm trying to string two (2) demos one after the other and want to stop the listen so I can restart it with a different set of parameters.

**Comment by jweisz** [comment]
Hi @plwodi, sorry for the huge delay in responding, I didn't seem to get notified of your issue when you first opened it.  As of now, `tj.listen()` cannot be terminated from within the playground. We didn't add support for a `tj.stopListen()` method because it wasn't necessary for the exercises we defined.

If you really need this functionality, it is possible to add support for it by adding support for `stopListen` in the playground and in the `tjbot-daemon`. Note that [tjbotlib](https://github.com/ibmtjbot/tjbotlib) does actually support `tj.stopListen()`, so it's just a matter of adding a new command in the playground and in the `tjbot-daemon`.  But again, we felt it was better to keep things simple by omitting it.
