### ISSUE TITLE
Error Compiling Source

### ISSUE THREAD

**Issue by mrjithesh** [jweisz/tjbot-playground#5]
I get this error when I try the playground file on my iPad

![img_0401](https://user-images.githubusercontent.com/8704633/48128252-fd48fe00-e2d9-11e8-995e-d8a4cd754c29.PNG)

**Comment by jweisz** [comment]
It looks like you downloaded the playground from the master branch and tried using it with Swift Playgrounds 2.1. I had some changes staged on the master branch to support Swift Playgrounds 2.2, but hadn't published a release yet, so that's why the playground didn't work for you.

Now that Swift Playgrounds 2.2 has been released, I just published an updated TJBot playground (v2.4) and updated the subscription feed. Please update your Playgrounds app and subscribe to the TJBot playground in the app, it should all "just work" now. ;)

Please re-open the issue if you still have trouble, and thanks for your interest!

**Comment by mrjithesh** [comment]
Thanks a lot,

Works now. Trying to get my daughter to explore coding. Thanks so much for your work.
